### ISSUE TITLE
Build fails on windows

### ISSUE THREAD

**Issue by truedat101** [huntlabs/cache#1]
Cool project idea, would like to see ldc2 and multi-platform support.  You can ship prebuilts for other platforms in your lib dir.  Build fails on windows 10.

$ !dub
dub test --compiler=ldc2
Fetching cache 0.0.3 (getting selected version)...
Fetching kiss 0.3.4 (getting selected version)...
Fetching dredis 0.0.7 (getting selected version)...
Fetching libmemcached 1.1.0 (getting selected version)...
Generating test runner configuration 'shell-d-test-library' for 'library' (library).
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Performing "unittest" build using ldc2 for x86_64.
dredis 0.0.7: building configuration "library"...
..\..\..\..\..\AppData\Roaming\dub\packages\dredis-0.0.7\dredis\source\redis\connection.d(143,17): Error: undefined identifier EWOULDBLOCK
ldc2 failed with exit code 1.

**Comment by zoujiaqing** [comment]
OK, this error from dredis project.

Let my team to see.

**Comment by zhangyuchun** [comment]
@truedat101 support now.

**Comment by truedat101** [comment]
Thanks, looks like these are the related commits:

0eeab5911e3973f8146998fe03cfa78bd0cfb120
5387f555ac6efcb6ca989cceb2aed9b50f9335ce
0eeab5911e3973f8146998fe03cfa78bd0cfb120

I'll rebuild with latest code.

**Comment by truedat101** [comment]
Verified build:
$ dub build --compiler=ldc2
Fetching libmemcached 1.1.1 (getting selected version)...
Fetching dredis 0.0.8 (getting selected version)...
Performing "debug" build using ldc2 for x86_64.
cache 0.0.4: building configuration "default"...

**Comment by truedat101** [comment]
Fails test:

$ dub test --compiler=ldc2
Generating test runner configuration 'cache-test-default' for 'default' (library).
Excluding package.d file from test due to https://issues.dlang.org/show_bug.cgi?id=11847
Performing "unittest" build using ldc2 for x86_64.
dredis 0.0.8: building configuration "library"...
..\..\..\AppData\Roaming\dub\packages\dredis-0.0.8\dredis\source\redis\connection.d(147,17): Error: undefined identifier EWOULDBLOCK
ldc2 failed with exit code 1.

**Comment by truedat101** [comment]
Obviously that failure is someone else's code.  I'll file a bug over there.

**Comment by zhangyuchun** [comment]
dredis also my team's library.  I didn't consider win64 env . your can try it later when dub package have dredis 0.0.9.

**Comment by truedat101** [comment]
Ok, ok, didn't know.  I've worked on TinyRedis a bit to add pub/sub support, but glad to see there is another package available that supports redis.

**Comment by truedat101** [comment]
I'm on a quest to improve platform support for modules that are useful in the dub repository.

**Comment by truedat101** [comment]
Cool, so this was fixed with: 0eeab5911e3973f8146998fe03cfa78bd0cfb120 ?  Thank you.
